/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ErrorView: typeof import('./src/components/cards/ErrorView.vue')['default']
    I18nCard: typeof import('./src/components/I18nCard/I18nCard.vue')['default']
    I18nCardWithList: typeof import('./src/components/I18nCard/I18nCardWithList.vue')['default']
    MarkdownContainer: typeof import('./src/components/utils/MarkdownContainer.vue')['default']
    PartnerCard: typeof import('./src/components/cards/PartnerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidemenuEntry: typeof import('./src/components/TheSidemenu/SidemenuEntry.vue')['default']
    TheDisclaimerDialog: typeof import('./src/components/TheDisclaimerDialog.vue')['default']
    TheLanguageToggle: typeof import('./src/components/utils/TheLanguageToggle.vue')['default']
    TheSidemenu: typeof import('./src/components/TheSidemenu/TheSidemenu.vue')['default']
    TheSocialContactMenu: typeof import('./src/components/utils/TheSocialContactMenu.vue')['default']
    UnderConstructionCard: typeof import('./src/components/cards/UnderConstructionCard.vue')['default']
  }
}
