/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    ContainerOfArticles: typeof import('./src/components/ContainerOfArticles.vue')['default']
    DisclaimerDialog: typeof import('./src/components/DisclaimerDialog.vue')['default']
    ErrorView: typeof import('./src/components/ErrorView.vue')['default']
    I18nCard: typeof import('./src/components/i18nCard.vue')['default']
    I18nCardWithList: typeof import('./src/components/i18nCardWithList.vue')['default']
    MarkdownContainer: typeof import('./src/components/MarkdownContainer.vue')['default']
    PartnerCard: typeof import('./src/components/PartnerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidemenuEntry: typeof import('./src/components/TheSidemenu/SidemenuEntry.vue')['default']
    TheSidemenu: typeof import('./src/components/TheSidemenu/TheSidemenu.vue')['default']
    UnderConstructionCard: typeof import('./src/components/UnderConstructionCard.vue')['default']
  }
}
