/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EntypoLeaf: typeof import('./src/components/utils/icons/EntypoLeaf.vue')['default']
    ErrorView: typeof import('./src/components/cards/ErrorView.vue')['default']
    FluentMegaphoneLoud20Filled: typeof import('./src/components/utils/icons/FluentMegaphoneLoud20Filled.vue')['default']
    GameIconsHand: typeof import('./src/components/utils/icons/GameIconsHand.vue')['default']
    HealthiconsMouth: typeof import('./src/components/utils/icons/HealthiconsMouth.vue')['default']
    I18nCard: typeof import('./src/components/cards/I18nCard/I18nCard.vue')['default']
    I18nCardWithList: typeof import('./src/components/cards/I18nCard/I18nCardWithList.vue')['default']
    IcOutlineMedication: typeof import('./src/components/utils/icons/IcOutlineMedication.vue')['default']
    IcOutlineTask: typeof import('./src/components/utils/icons/IcOutlineTask.vue')['default']
    MarkdownContainer: typeof import('./src/components/utils/MarkdownContainer.vue')['default']
    MingcuteArrowRightFill: typeof import('./src/components/utils/icons/MingcuteArrowRightFill.vue')['default']
    PartnerCard: typeof import('./src/components/cards/PartnerCard.vue')['default']
    RibbonComponent: typeof import('./src/components/utils/RibbonComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidemenuEntry: typeof import('./src/components/TheSidemenu/SidemenuEntry.vue')['default']
    TheDisclaimerDialog: typeof import('./src/components/utils/TheDisclaimerDialog.vue')['default']
    TheLanguageToggle: typeof import('./src/components/utils/TheLanguageToggle.vue')['default']
    TheSidemenu: typeof import('./src/components/TheSidemenu/TheSidemenu.vue')['default']
    TheSocialContactMenu: typeof import('./src/components/utils/TheSocialContactMenu.vue')['default']
    UnderConstructionCard: typeof import('./src/components/cards/UnderConstructionCard.vue')['default']
  }
}
